site_name: PinkLion Documentation

theme:
  name: material
  palette:
    # primary: pink
    primary: deep purple
    accent: deep purple
  font:
    text: Open Sans    
  logo: docs/assets/img/lion-head.png
  favicon: docs/assets/img/favicon-32x32.png
  features:
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.tracking
      - navigation.instant
      # - toc.integrate
hide:
  - navigation
nav:
    - Home: 'docs/index.md'
    - Platform Architecture: 'docs/platform-architecture.md'
    - Portfolio Optimizer: 'docs/portfolio-optimizer.md'
extra:
  homepage: https://pinklion.xyz
# extra_css:
#   - stylesheets/extra.css  
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - attr_list
  - md_in_html  
  - admonition
  - abbr
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true  
  - pymdownx.caret
  - pymdownx.tilde    