site_name: PinkLion Documentation

theme:
  name: material
  palette:
    # primary: pink
    primary: deep purple
    accent: deep purple
  font:
    text: Open Sans    
  logo: docs/assets/img/lion-head.png
  favicon: docs/assets/img/favicon-32x32.png
  features:
      - navigation.tabs
      - navigation.tracking
      - navigation.instant
      # - toc.integrate
hide:
  - navigation
nav:
    - Home: 'docs/index.md'
    - Platform Architecture: 'docs/platform-architecture.md'
    - Portfolio Optimizer: 'docs/portfolio-optimizer.md'
extra:
  homepage: https://pinklion.xyz
# extra_css:
#   - stylesheets/extra.css  
markdown_extensions:
  - attr_list
  - md_in_html  